### ISSUE TITLE
Consider upstreaming to rules_go

### ISSUE THREAD

**Issue by fmeum** [phst/runfiles#3]
I started a discussion in https://github.com/bazelbuild/rules_go/issues/3036 to get this library upstreamed as `@io_bazel_rules_go//go/runfiles`. According to https://github.com/bazelbuild/rules_go/issues/3036#issuecomment-997966804, this would require more definite upstream documentation on what a runfiles library should do. It probably makes sense to wait for https://github.com/bazelbuild/bazel/issues/14336 and https://github.com/bazelbuild/bazel/issues/14500 to be resolved first though.

**Comment by phst** [comment]
Related: the discussion starting at https://github.com/bazelbuild/rules_go/issues/2422#issuecomment-612985043

> more definite upstream documentation on what a runfiles library should do

I think that makes sense. Maybe file another bug against Bazel to track adding the documentation?

**Comment by fmeum** [comment]
I can take care of that after the open issues have been resolved, which will make it easier to arrive at a definite version of that documentation.

(Not completely related, but do you perhaps happen to know someone I could @ to take a look at https://github.com/bazelbuild/bazel/issues/14336?)

**Comment by phst** [comment]
This has happened: https://pkg.go.dev/github.com/bazelbuild/rules_go/go/runfiles
